src/textUI/CommandLineClient.java

Jeg har opdateret start beskeden på spillet samt nogle andre beskeder til brugeren i CLI'en
Closes #6

Updated CommandLineClient.java

---

src/Item.java

added Item Class

---

src/Game.java

Changed rooms

---

src/Game.java

Changed rooms, added container room

---

src/Bucket.java
src/Item.java
src/Tools.java

Har oprettet en abstract tools klasse, samt lavet en Bucket klasse som nedarver fra denne.
Det er muligt at adde instanser af Item klassen til Bucket som indeholder en arraylist.
Det er muligt at se typen af Item som Bucket indeholder (ved hjælp af getType fra Item klassen)
Det er muligt at tømme spanden (sletter alt i arraylisten i spanden)
Closes #10

Har lavet Bucket samt Tools class

---

src/Bucket.java
src/Interactable.java
src/Inventory.java
src/Item.java
src/Plastic.java
src/Tools.java

har tilføjet alle de nye klasser og metoder som matcher vores UML diagram

nye klasser og metoder

---

src/textUI/Parser.java

Alt input bliver converted til lower case, sådan at spillet er ligeglad med om du skriver med caps lock, da alt alligevel bliver til lower case som den forstår.

Fikset case sensitivity

---

src/Game.java
src/Room.java

Det er nu muligt at putte items i rummene ved hjælp af .setItems, ligesom med .setExit 
Hver gang man skifter rum bliver der også vist hvilke items (hvis der er nogle) der er i rummet

items added to rooms

---

src/Captain.java
src/Game.java
src/NPC.java
src/Room.java

Det er nu muligt at tilføje NPC til rummene, ved hjælp af .setNPC samt der bliver ved rumskift vist (hvis nogle) hvilke NPC'er der er i det pågældende rum
Der er tilføjet en abstrakt klasse NPC
Der er tilføjet en Captain klasse
closes #27

added npc to room, added NPC class, added Captain class

---

src/Captain.java
src/Commands.java
src/Game.java
src/NPC.java
src/Room.java
src/textUI/CommandLineClient.java

added talk command

---

.gitignore
.idea/.gitignore
.idea/libraries/fasterxml_jackson_core_databind.xml
.idea/misc.xml
.idea/modules.xml
.idea/uiDesigner.xml
.idea/vcs.xml
semesterproject-team3.2.iml
src/data/DataParser.java
test.json

Json backend

---

.gitignore
.idea/.gitignore
.idea/libraries/fasterxml_jackson_core_databind.xml
.idea/misc.xml
.idea/modules.xml
.idea/uiDesigner.xml
.idea/vcs.xml
semesterproject-team3.2.iml
src/Captain.java
src/Game.java
src/Worker.java
src/data/DataParser.java
src/textUI/CommandLineClient.java
test.json

Added class Worker
moved NPC
added NPC
added tekst for conversation with NPC's

Brugervejledning

---

src/Bucket.java
src/Commands.java
src/Game.java
src/Inventory.java
src/Plastic.java
src/Room.java
src/textUI/CommandLineClient.java

Jeg har implementeret get commanden sådan at den fungerer efterfulgt af et item navn
Dog kan man kun samle Plastic op, men ikke Bucket fx - Dette skal jeg lige have kigget på, men ellers fungerer alt efter hensigten
closes #36

Get command

---

src/Game.java

made the loop continue instead of returning false, if the item name wasn't the first one in the list of items in the room
so it is now possible to pick up a bucket even if it is the at the last index of the item list in the room :D

fixed loop in getCommand

---

src/Bucket.java
src/Game.java
src/Inventory.java

Plastic will now be added to the bucket, if the player inventory contains one. 
There is no empty method yet, but soon to come :D

Bucket implementation

---

src/Bucket.java
src/Commands.java
src/Game.java
src/textUI/CommandLineClient.java

added empty command 
closes #40

added empty command

---

src/GUI/PlayerMove.java

fixed movement animation. moonwalk feature is available!!

---

src/GUI/GameApplication.java
src/GUI/PlayerMove.java
src/GUI/dock.fxml

added borders for the player
had to hardcode the size of the scene, since scene.getWidth and getHeight wouldn't work no matter what i did
so had to make 2 final attributes in playermove, and also made the scene non resizable so borders always match
also made the movement variable 10 becaues i got tired of moving slow :D

added borders

---

src/domain/Commands.java
src/domain/Game.java
src/domain/Minigame.java
src/domain/Room.java
src/textUI/CommandLineClient.java

added minigame

---

src/textUI/CommandLineClient.java

minigame works with the empty command aswell

Bugfix minigame

---

.idea/libraries/openjfx_javafx_controls.xml
.idea/libraries/openjfx_javafx_fxml.xml
src/GUI/GameController.java
src/GUI/game.fxml
src/data/roomdescriptions/ship.json
src/domain/Captain.java
src/domain/Game.java
src/domain/Worker.java

changed the talk with npc to be in the pop up box
centered the text for welcome and minigame end
also added a different dialog for worker when you haven't spoken to the captain yet

Pop up box talk
